"""initial tables

Revision ID: e68626a7f654
Revises:
Create Date: 2026-03-01 17:23:59.509024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e68626a7f654"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("image", sa.String(length=500), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "exams",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "ocr_processing",
                "parsing",
                "grading",
                "analyzing",
                "generating",
                "completed",
                "failed",
                name="exam_status",
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column(
            "file_key",
            sa.String(length=500),
            nullable=False,
            comment="Cloud storage object key",
        ),
        sa.Column(
            "file_type",
            sa.String(length=50),
            nullable=False,
            comment="image/jpeg, image/png, application/pdf",
        ),
        sa.Column("raw_ocr_text", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=True),
        sa.Column("correct_count", sa.Integer(), nullable=True),
        sa.Column("incorrect_count", sa.Integer(), nullable=True),
        sa.Column("accuracy_rate", sa.Float(), nullable=True),
        sa.Column(
            "statistics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Category stats, radar data, summary",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exams_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exams")),
    )
    op.create_index(
        op.f("ix_exams_user_id"), "exams", ["user_id"], unique=False
    )
    op.create_table(
        "exam_questions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "multiple_choice",
                "subjective",
                name="question_type",
            ),
            nullable=False,
        ),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "choices",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='["A) ...", "B) ...", ...]',
        ),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column("user_answer", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column(
            "similarity_score",
            sa.Float(),
            nullable=True,
            comment="Semantic similarity for subjective (0.0-1.0)",
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_exam_questions_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_exam_questions")
        ),
    )
    op.create_index(
        op.f("ix_exam_questions_exam_id"),
        "exam_questions",
        ["exam_id"],
        unique=False,
    )
    op.create_table(
        "practice_sets",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment=(
                '[{"question": "...", "choices": [...], "answer": "..."}]'
            ),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_practice_sets_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_practice_sets")
        ),
    )
    op.create_index(
        op.f("ix_practice_sets_exam_id"),
        "practice_sets",
        ["exam_id"],
        unique=False,
    )
    op.create_table(
        "weakness_analyses",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column(
            "sub_category", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "error_type", sa.String(length=255), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_weakness_analyses_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_weakness_analyses")
        ),
    )
    op.create_index(
        op.f("ix_weakness_analyses_exam_id"),
        "weakness_analyses",
        ["exam_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_weakness_analyses_exam_id"),
        table_name="weakness_analyses",
    )
    op.drop_table("weakness_analyses")
    op.drop_index(
        op.f("ix_practice_sets_exam_id"),
        table_name="practice_sets",
    )
    op.drop_table("practice_sets")
    op.drop_index(
        op.f("ix_exam_questions_exam_id"),
        table_name="exam_questions",
    )
    op.drop_table("exam_questions")
    op.drop_index(
        op.f("ix_exams_user_id"), table_name="exams"
    )
    op.drop_table("exams")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
